### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by osafaimal** [Nickwasused/FreeGamesonSteam#37]
**Describe the bug**
i don t understand the code neither the problem thus i report here

**To Reproduce**
1. run the script
2. See error

**Expected behavior**
'Not using Proxy Servers'
Traceback (most recent call last):
  File "\FreeGamesonSteam-master.140\steam.py", line 214, in <module>
    querygames()
  File "FreeGamesonSteam-master.140\steam.py", line 208, in querygames
    _ = json.loads(_)
  File "C:\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 49 (char 48)

**Please complete the following information:**
 - OS: Ubuntu 20.04.2 LTS and  Windows 10.0.19042.1052
 - python version: 3.8.5 and 3.9.1

**Additional context**
 - Script Version (Maybe it just needs an update): 140
 - Is the Problem caused by the Script or ArchiSteamFarm?

**Comment by Nickwasused** [comment]
Can you send your **steamconfig.py** without your Steamid and Steam API Key?

**Comment by osafaimal** [comment]
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Nickwasused

class config:
    # Config /Example for Bot (asf) bot_names = ["asf"]
    # !Important please change the Settings here!
    bots = []

    # e.g multiple bots
    # bots = ['{"name": "YOUR_BOT_NAME", "steamid": "YOUR_STEAM_ID_64"}, {"name": "YOUR_BOT_NAME_2", "steamid": "YOUR_STEAM_ID_64_2"}']


    boturl = 'http://127.0.0.1:1242/Api/Command/'
    botip = '127.0.0.1'
    boturl = 'http://localhost:1242/Api/Command/'

    # Log Default: true
    log = 'true'
    # Logfile Default: freegames-log
    logfile = 'freegames.log'
    # Proxys are disabled by default
    proxy = 'disabled'
    # Timeout for redeeming Keys: Default 2 Seconds
    timeout = 2

    #You dont need to change things here:
    links = ['https://steamdb.info/sales/?min_discount=95&min_rating=0', 'https://steamdb.info/upcoming/free/#live-promotions']
    basesteam = 'https://store.steampowered.com/app/'

    def getsteamapilink(self, steamid):
        steam_api_key = ""
        return "https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key={}&steamid={}&format=json".format(steam_api_key, steamid)

    # You can change the User Agent here:
    # Default: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail appname/appversion
    headers = {
        'User-Agent': 'Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail appname/appversion'
    }

**Comment by Nickwasused** [comment]
There seems to be a Problem with your config but I can´t find it.

For comparison this is my config file:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Nickwasused

class config:
    # Config /Example for Bot (asf) bot_names = ["asf"]
    # !Important please change the Settings here!
    bots = ['{"name": "main", "steamid": "Your Steam ID should be here"}']

    # e.g multiple bots
    # bots = ['{"name": "YOUR_BOT_NAME", "steamid": "YOUR_STEAM_ID_64"}, {"name": "YOUR_BOT_NAME_2", "steamid": "YOUR_STEAM_ID_64_2"}']


    boturl = 'http://127.0.0.1:1242/Api/Command/'
    botip = '127.0.0.1'
    boturl = 'http://localhost:1242/Api/Command/'

    # Log Default: true
    log = 'true'
    # Logfile Default: freegames-log
    logfile = 'freegames.log'
    # Proxys are disabled by default
    proxy = 'disabled'
    # Timeout for redeeming Keys: Default 2 Seconds
    timeout = 2

    #You dont need to change things here:
    links = ['https://steamdb.info/sales/?min_discount=95&min_rating=0', 'https://steamdb.info/upcoming/free/#live-promotions']
    basesteam = 'https://store.steampowered.com/app/'

    def getsteamapilink(self, steamid):
        # https://steamcommunity.com/dev/apikey
        steam_api_key = "Your Steam API Key should be here"
        return "https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key={}&steamid={}&format=json".format(steam_api_key, steamid)

    # You can change the User Agent here:
    # Default: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail appname/appversion
    headers = {
        'User-Agent': 'Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail appname/appversion'
    }
```

**Comment by Nickwasused** [comment]
Please See #39
